### ISSUE TITLE
Frontend / Backend Feature Tracking

### ISSUE THREAD

**Issue by jnolan-poloniex** [joshmiller17/vennt-server#6]
## Character Management
* Attribute management
- [ ] Backend - add an `adjust_attributes` api that can adjust multiple character attributes at once.
* Ability management
- [ ] Backend - add which path abilities come from when doing web scraping
- [ ] Backend - when scraping web text, if the first lines are italic, note it as `flavor` and don't include that text in the main description.
- [ ] Frontend - keep track of the total amount of XP spent
* Create item / weapon shop
- [ ] Backend - Support characters owning an item container with item name, bulk capacity, and description. Ideally we would have an API for returning all available (https://vennt.fandom.com/wiki/Item_Containers)
- [ ] Backend - would be great if we made an API to return all item options instead of storing info on both frontend and backend (https://vennt.fandom.com/wiki/Equipment & https://vennt.fandom.com/wiki/Consumables)
- [ ] Frontend - need to make new page for this - probably accessible on character management side

## Enemy Management
- [ ] Backend - support enemy abilities / custom enemy abilities.
- [ ] Backend - Allow for enemies to be copied and renamed if multiple are needed for a fight.
- [ ] Frontend - Make enemy creation page
  - [ ] Allow you to import specific numbers (re-purpose character import page)
  - [ ] Allow you to make an enemy as a character (see https://vennt.fandom.com/wiki/Course_of_Combat, re-use character creation flow)
  - [ ] Allow you to import enemies from the bestiary (https://vennt.fandom.com/wiki/Category:Bestiary)
  - [ ] Allow you to create new enemies (see https://vennt.fandom.com/wiki/Course_of_Foes)

## Campaigns / Combat
- [ ] Backend - add a log for all combat / campaign actions so everyone can see a history of what's happening
- [ ] Backend - add an endpoint for rolling attribute checks and adds result to log. Should be able to optionally provide your roll or the server will roll for you (see initiative example: https://github.com/joshmiller17/vennt-server/blob/main/api_initiative.py#L48-L56)
- [ ] Backend - create some utility function for rolling dice
  - [ ] Should support Flow / Ebb
  - [ ] Should support using a hero point - e.g. roll 3d6 + 9 and drop the lowest dice
- [ ] Backend - add API for modifying entity details - e.g. number of `actions` / `reactions` / `gm_only` etc.
- [ ] Backend - add basic API for creating an attack
  - [ ] supports taking target & damage / accuracy numbers
  - [ ] supports taking target & weapon & optional roll
- [ ] Backend - API for responding to an attack.
  - [ ] supports inputing damage taken
  - [ ] supports allowing server to calculate and apply damage (e.g. using your vim, checking if its a glancing blow, etc.)
  - [ ] supports commonly used special cases:
    - [ ] blocking attacks (if entity has ability)
    - [ ] dodging attacks (if entity has ability)
- [ ] Backend - when starting a new turn, allow the number of actions / reactions received to be modified in some way (maybe a constant in the entities table? Ideally we should be able to track where bonuses are coming from / when they are supposed to end. Maybe a solution here can be generalized for other campaign / combat features)
- [ ] Frontend - implement sending campaign invites
- [ ] Frontend - implement updating user roles if campaign owner
- [ ] Frontend - implement spectator campaign view
- [ ] Frontend - implement character campaign view
- [ ] Frontend - implement GM campaign view
- [ ] Frontend - add easy enemy insertion from enemy creator for GMs

**Comment by joshmiller17** [comment]
- Why do we need `adjust_attributes`?
- Path info should be available in abilities.json
- I think feature for enemy copying already exists, unless it was only the Discord bot that could do that, I can check
- Note that basically everything on the Bestiary probably needs to be updated
- Rolling dice is already supported; again, we want the server to handle low-level rolling, frontend can calculate flow etc. I'm fine with a function for "change the lowest to 9" for hero point usage.

**Comment by jnolan-poloniex** [comment]
`adjust_attributes` would help for when I want to adjust a bunch of character attributes at once so I can do it with 1 API call instead of 2 or 3.
- I don't think enemy copying exists right now in the code base
- good to know about the bestiary - it looks like there are a couple of enemies in there that look fine? E.g. https://vennt.fandom.com/wiki/Thunder_Lizard
- I think I've had a change of heart on handling dice rolling - I would really like to support manually rolling dice (like in real life) or allowing the frontend to roll dice. Since users can input information for everything else, this doesn't seem too strange. Rolling dice is handled in the sense that we have `d20`, not in the sense that we have some centralized utility that we can use to handle all of the weird edge cases etc.

**Comment by jnolan-poloniex** [comment]
Or instead of making a new API like `adjust_attributes`, we could update `set_attribute` to be able to update multiple attributes at once

**Comment by joshmiller17** [comment]
> Or instead of making a new API like `adjust_attributes`, we could update `set_attribute` to be able to update multiple attributes at once

I prefer this approach. Better yet might be to replace `set_attribute` with a  `set_attributes` call that takes a list (though that list can be only one element). Up to you.

**Comment by joshmiller17** [comment]
> `adjust_attributes` would help for when I want to adjust a bunch of character attributes at once so I can do it with 1 API call instead of 2 or 3.
> 
> * I don't think enemy copying exists right now in the code base
> * good to know about the bestiary - it looks like there are a couple of enemies in there that look fine? E.g. https://vennt.fandom.com/wiki/Thunder_Lizard
> * I think I've had a change of heart on handling dice rolling - I would really like to support manually rolling dice (like in real life) or allowing the frontend to roll dice. Since users can input information for everything else, this doesn't seem too strange. Rolling dice is handled in the sense that we have `d20`, not in the sense that we have some centralized utility that we can use to handle all of the weird edge cases etc.

I'm not sure if Thunder Lizard's stats are correct as of the latest L-based function on the Foes page, though I'm not sure it matters a great deal.

Regarding rolling, I would be perfectly fine with having rolls be client-side rather than server-side. Although I think we should provide a single roll utility where the client can specify a rollstring and we simply return how d20 parses it.
